name: CI/CD

on:
  push:
    branches:
      - "**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest
          build-args: |
            NEXT_API_URL=${{ secrets.NEXT_API_URL}}
            SITE_URL=${{ secrets.SITE_URL }}

  deploy:
    needs: docker
    runs-on: self-hosted
    steps:
      - name: Pull latest image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest

      - name: Stop & remove old container
        run: |
          docker stop nextjs-app || true
          docker rm   nextjs-app || true

      - name: Run container
        run: |
          docker run -d --name nextjs-app \
            -p 3000:3000 \
            --restart=always \
            -e NEXT_API_URL='${{ secrets.NEXT_API_URL }}' \
            -e SITE_URL='${{ secrets.SITE_URL }}' \
            ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest
